### PR TITLE
Allow passing custom MenuStyle to dialog functions

### PR DESCRIPTION
**Pull request by Lynesth**

### CODE REVIEW

**Comment by AydinHassan** [comment]
I'm not really sold on this - I'm not a fan of keep tacking on extra parameters, it looks a bit wonky - although I can't think of another way to achieve it. Maybe you have an idea @mikeymike or thoughts in general?

**Comment by AydinHassan** [comment]
It is possible to modify the styles, both the dialogues and inputs expose a `getStyle` method which allows you to customise.

 However, if thats still not enough I been happy with either a `withStyle` method on the inputs and dialogues or a secondary style object stored on `CliMenu` which is used for all dialogues and inputs.

**Comment by mikeymike** [comment]
My .2c 

I think having the methods globally on the `MenuStyle` makes the most sense, you don't want to have to pass around the object or have to define the style for every dialog. 

However I like the option to have a `withStyle` or `getStyle` which would allow someone to override those for other use cases such as big alerts, warning alerts etc etc

I think I've spoken to @AydinHassan about this before but one thing I'd really think would be awesome is having a CSS like approach to the styles, we'd need to classify stylable areas etc but it would make it easier for the end user

**Comment by Lynesth** [comment]
I totally overlooked the getStyle() function. Yeah so that allows for customization.

**Comment by AydinHassan** [comment]
@Lynesth you think `getStyle` is enough or would `withStyle` be a nice addition?

**Pull request merged**
