### PR TITLE
WIP: Inputs

### PR DESCRIPTION
**Pull request by AydinHassan**

### CODE REVIEW

**Comment by mfour-merickson** [comment]
@AydinHassan Is there a technical reason for having minimum PHP as 7.2, that is quite restricting and I am going to have to yank this out of my project (or continue using the current version I have installed)

**Comment by AydinHassan** [comment]
Not really - it would probably be a new major version for these features anyway. To be honest I didn't even mean to push that commit - that was laying around from a while ago. I guess we could go down to 7.1 but it's definitely time for a bump.

**Comment by mikeerickson** [comment]
I think a jump to 7.1 would be acceptable, but 7.2 is drastic for us (then I would have to deploy our tool w/ a special docker container which contains 7.2

Our internal dev team is in process of moving from 7.0.23 -> 7.1 and that took and act of Congress :)

Please consider reducing requirement to 7.1

**Comment by AydinHassan** [comment]
Bumped to `7.1` in #79. This will need rebasing off master when that is reviewed + merged.

**Comment by AydinHassan** [comment]
closing in favour of #81

**Pull request closed without merging**
