### PR TITLE
Add gitattributes

### PR DESCRIPTION
**Pull request by vinkla**
This will remove unesseccary files for production use.

### CODE REVIEW

**Comment by AydinHassan** [comment]
Thanks!

**Comment by vinkla** [comment]
Anytime!

**Comment by AydinHassan** [comment]
It doesn't actually work on Windows yet!

**Comment by vinkla** [comment]
Okay, I see. Thanks for explaining.

**Comment by AydinHassan** [comment]
Something we need to work on but it's so damn tricky 😭

**Comment by vinkla** [comment]
To bad :disappointed:

**Pull request merged**
