### PR TITLE
Add emacs style up/down shortcuts ctrl+n and ctrl+p

### PR DESCRIPTION
**Pull request by lachlankrautz**

### CODE REVIEW

**Comment by AydinHassan** [comment]
@lachlankrautz am I missing something here? they just seem like empty strings in the GitHub diff?

**Comment by AydinHassan** [comment]
Seems it's just GH. I pulled and it looks fine. Thanks!

**Comment by AydinHassan** [comment]
I tagged `2.1.0` which your changes in :)

**Comment by lachlankrautz** [comment]
Awesome, thank you!

**Pull request merged**
