### PR TITLE
Commonise duplicated assertion in CliMenu.

### PR DESCRIPTION
**Pull request by thehereward**

### CODE REVIEW

**Comment by AydinHassan** [comment]
Hi, thanks! This failed the CS checks as underscored methods are not allowed! I can make this change later if you don't have time? You can ignore the appveyor build failure. I will be removing that from PR's soon.

**Comment by thehereward** [comment]
No problem, I can take the underscores out now - old habits die hard!

**Comment by AydinHassan** [comment]
Thanks!

**Comment by AydinHassan** [comment]
I'll get to the other tomorrow, just about to fly 😊

**Pull request merged**
