### PR TITLE
Fixed problem with package installation on Windows

### PR DESCRIPTION
**Pull request by Igoriankrg**
This update needs to prevent usage "composer install --ignore-platform-reqs" everytime on Windows (not posix system).
Source of idea - https://stackoverflow.com/a/52778992

### CODE REVIEW

**Comment by AydinHassan** [comment]
@Igoriankrg we're pretty sure it doesn't work on windows. Have you been using it and found any issues? It has been a long time since we tried.

**Comment by AydinHassan** [comment]
Just to be clear, we do use posix functions, so the requirement is necessary. The library simply won't work without them.

**Comment by Igoriankrg** [comment]
I agree with it (i think nobody use Windows to host their applications), but for developers on Windows it would be nice convenience update.

**Comment by AydinHassan** [comment]
@Igoriankrg we use posix functions. See: https://github.com/php-school/terminal/blob/master/src/IO/ResourceInputStream.php#L45 which is a direct requirement of `php-school/cli-menu`. This change would allow to install `cli-menu` on an environment where the code does not function correctly.

**Comment by Igoriankrg** [comment]
I cannot image more suitable way out. So "composer install --ignore-platform-reqs" for Windows users is to know about the code does not function correctly on this environment.

**Pull request closed without merging**
