### PR TITLE
Refresh only needed rows

### PR DESCRIPTION
**Pull request by Lynesth**
Instead of the whole menu each time you move up and down in selections.
It performs much better and prevents a lot of stuttering.

I wasn't sure how I was supposed to launch the tests and such but I suspect that Travis will do it.

I don't make a lot of PRs on github, so let me know if I overlooked something regarding this process or if I didn't understand your coding standards.

Edit: I juste realized you use spaces instead of tabs, will fix this if tests are good.

Edit n°2: I could have used `moveCursorToRow()` instead of `moveCursorToTop() + moveCursorDown()` but performances are unexpectedly better using the latter.

Edit n°3: What I did with `drawMenuItem()` and `addRows()` isn't pretty, but I intended to keep BC without touching much of the code.

Edit n°4: Note sure how to add tests to hit those new lines, Codecov seems angry :)

### CODE REVIEW

**Comment by mikeymike** [comment]
hey @Lynesth thanks for the PR!

Love the idea of this however change in output might not just be from moving up or down and it would be cool to have it handle most or all of those cases. 

Tagging @AydinHassan in this for more discussion as I think this could be a good starting point or at least spark of some great ideas

**Comment by Lynesth** [comment]
Hello @mikeymike 

Yeah, I was thinking about it and I have a much better way of doing it. Finishing the new PR, you can close this one if you want (I will start from a new branch).

**Comment by mikeymike** [comment]
Looking forward to it, there's a bunch of new things going into master recently so a great time to add new stuff, just remember to keep your local up to date to limit conflicts

**Comment by Lynesth** [comment]
Yeah I noticed the changes, with Terminal moving to its own repo and all. That's why I'm starting over.

I just don't know... I'll need to make 2 PRs, one for CliMenu and one for Terminal, how am I supposed to do it so that tests can work ? I guess I need to make the Terminal one first and somehow refer to it in the CliMenu one ?

Any help would be welcome :)

**Comment by mikeymike** [comment]
@Lynesth I guess it would depend on what package "owns" the functionality and how you're going to structure it. Might be worth popping into our slack channel if you'd like to discuss 😄

**Pull request closed without merging**
