### PR TITLE
Updated Confirmation Dialog

### PR DESCRIPTION
**Pull request by ccsliinc**
Please look over the proposed changes to make the dialog box cancellable.  The proposed changes will not break any existing code.  The method remains the same with an additional argument, additional example added to source as well.

### CODE REVIEW

**Comment by ccsliinc** [comment]
ok i will fix and resubmit, give me a couple days.

**Comment by AydinHassan** [comment]
Sure, no rush!

**Comment by ccsliinc** [comment]
I uploaded a fixed PR.

**Review by AydinHassan — APPROVED** [review]

**Comment by AydinHassan** [comment]
Thanks for the contribution @ccsliinc !

**Pull request merged**
