### PR TITLE
Split ASCII art justification code into its own class.

### PR DESCRIPTION
**Pull request by thehereward**
I think this is a little bit of an improvement, but possibly not as much as I originally hoped it would be... But I enjoyed writing it so it's not necessarily all wasted effort.

It certainly separates out concerns (AsciiArtItem now no longer concerns itself with how to justify its contents) which I think is a bit easier to understand now. Whether its worth the addition of the extra class is a decision I'll leave up to you. :-)

### CODE REVIEW

**Comment by mikeymike** [comment]
Hey @thehereward thanks for the contributions and I'm glad your enjoying writing them :smile: 

I'm hoping to potentially add renderers at some stage for the menu items especially for the ascii art item as we need to prevent / replace art too large for the menu. Also it would be good to be able to apply justification to any of the items and not just the ascii art item. Your more than welcome to take a stab at that instead :+1: 

Also you more than welcome to join the [PHP School Slack channel](https://phpschool-team.slack.com/messages) if you want to discuss anything in more detail

**Comment by mikeymike** [comment]
sorry dude didn't mean to close this :)

**Comment by thehereward** [comment]
Haha, no problem. I expect it would have come back in a different form for renderers anyway.

I think there are three different issues in your comment:

*[Don't output ascii art if it doesn't fit](#5)*
We can resolve this fairly easily on top of this change without doing the other two changes.

*Adding Renderers*
The simplest way would be to move the 'getRows' logic for each menu item into the renderer class for that item. We could then go on to move the drawMenuItem logic into a menu item renderer and reduce the top level method to something along the lines of:
```php
protected function drawMenuItem(MenuItemInterface $item, $selected)
{
    $renderer = $item->getRenderer($this->style, $selected);
    echo $renderer->render();
}
```

*Justify all menu items*
Do you imagine this working in the same way as with AsciiArt - the position can be set individually for each menu item and defaults to something sensible for each type? (We could also add a default to the MenuStyle but I suspect it makes more sense to have different menu items defaulting to different positions like currently have).

**Comment by thehereward** [comment]
I realise I've written quite a lot and not really come up with any sort of plan.

Shall I raise issues for the two items that don't currently have them and then make a start at one of them? Probably the renderers.

**Comment by mikeymike** [comment]
My main reservation with merging this in at the minute is it has a limited benefit over potentially a short term as it would realistically be re-written / removed during development of justify for all menu items. 

Not outputting ascii art if it doesn't fit would also be resolved fairly easily in the rendering process, I quiet like the idea of having a quirky feature here and display a placeholder / broken image type of ascii art instead. I also toyed with the idea of re-rendering on window resizing (but that's a whole different feature for another day / discussion) 

Now the best approach for implementing the renderer I'm not too sure about. I agree with what your suggesting and we could potentially have one renderer for selectable items as these are pretty much always going to be the same, then other items would have their own specific renderers. At this point we could go down a few routes, either implement a factory for the renderers so at the top level it would work more like,

```php 
protected function drawMenuItem(MenuItemInterface $item, $selected)
{
    $renderer = MenuItemRendererFactory::fromMenuItem($item);
    $renderer->render($this->style, $selected);
}
```

or we potentially pass the renderers to the menu items on construct in the `CliMenuBuilder` so it's like what you put, but I'd pass the style & selected params to the render method directly

```php 
protected function drawMenuItem(MenuItemInterface $item, $selected)
{
    $item->getRenderer()->render($this->style, $selected);
}
```

We could even go one step further and introduce a `CliMenuRenderer` and refactor the `draw` method out of `CliMenu` completely. 

I'm happy to go over this further in a new issue and @AydinHassan can chime in with any thoughts :smile: 

**Justify on all menu items**
I think your right here this is definitely a separate and worthy of its own issue :+1: The best bet would be to have a `justifySelectableItems` in the menuStyle and then unselectable menu items should have justify implement the same as the ascii art. Of course selectable menu items content width depends on whether or not the item extra is being shown at the end of any selectable item, so however we handle this would need to handle both 

Overall I think it would be great if we got the renderers in and then look into a separate solution for the justify on all items. 

Let me know what you think.

**Comment by thehereward** [comment]
Given what you've said I am happy with not merging this.

I like the idea of the 'quirky' broken ASCII art feature (and the resizing, although agree that is largely a different matter).

I will have a go at implementing the renderers - I think I do prefer the factory approach you suggest so that is how I will start :-)

**Comment by mikeymike** [comment]
Awesome stuff, Looking forward to it! :smile: 

I'll close this now, any issues / questions jump on Slack or just create an Issue on here :+1:

**Pull request closed without merging**
