### PR TITLE
Adds the ability to add multiple checkbox and radio items

### PR DESCRIPTION
**Pull request by octoper**
This PR adds the ability to add multipe checkbox and radio items at once.

# Examples:

## Checkbox 

```php
<?php

use PhpSchool\CliMenu\Builder\CliMenuBuilder;
use PhpSchool\CliMenu\CliMenu;

$callable = function (CliMenu $menu) {
    echo 'I am alive!';
};

$menu = (new CliMenuBuilder)
    ->addCheckboxItems([
        ['Item 1', $callable],
        ['Item 2', $callable],
        ['Item 3', $callable],
    ])
    ->build();
```

## Radio
```php
<?php

use PhpSchool\CliMenu\Builder\CliMenuBuilder;
use PhpSchool\CliMenu\CliMenu;

$callable = function (CliMenu $menu) {
    echo 'I am alive!';
};

$menu = (new CliMenuBuilder)
    ->addRadioItems([
        ['Item 1', $callable],
        ['Item 2', $callable],
        ['Item 3', $callable],
    ])
    ->build();
```

### CODE REVIEW

**Review by mikeymike — COMMENTED** [review]
This looks good to me, We'll wait for CI to run but this looks like a nice addition cc @AydinHassan

**Comment by AydinHassan** [comment]
@octoper thanks for the perfect pr, tests, docs, examples. Will merge when travis runs, probably next week at this rate (it's very slow) 😭

**Comment by octoper** [comment]
Thinking about making a PR to move from TravisCI to GitHub actions.

**Comment by AydinHassan** [comment]
I did try before but there were some problems with the tty stuff we do. It is definitely welcome if you would like to have a crack!

**Comment by octoper** [comment]
cc @AydinHassan hopefully TravisCI passed 😅

**Comment by AydinHassan** [comment]
Thanks @octoper !

**Comment by octoper** [comment]
Do you need both https://codecov.io and https://scrutinizer-ci.com (sorry that I'm mention that hera but I don't know how to contact you)  cc @AydinHassan

**Comment by mikeymike** [comment]
@octoper  feel free to join us on Slack https://phpschool.herokuapp.com/

**Comment by AydinHassan** [comment]
We can drop scrutinizer, we have done for the other repos 🙂

**Pull request merged**
